### ISSUE TITLE
Confirmar transacciones

### ISSUE THREAD

**Issue by rcasalla** [MISO4203-201520/mp-usedVehicles#12]
Falta una confirmación al usuario antes de pagar. 
Comunicar que la pregunta fue enviada. Cómo va a contestar el proveedor?

**Comment by carmudgeon** [comment]
MUV-1 Confirmar transacciones

**Comment by carmudgeon** [comment]
MUV-1 Resolved

**Comment by carmudgeon** [comment]
![captura1](https://cloud.githubusercontent.com/assets/2287052/10115327/0bd6ee16-63c9-11e5-9483-95d681b6b876.PNG)
![captura2](https://cloud.githubusercontent.com/assets/2287052/10115328/0be13574-63c9-11e5-8391-2e618f3079ca.PNG)

**Comment by carmudgeon** [comment]
Se finaliza el desarrollo de la mejora propuesta
