### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by rcasalla** [MISO4203-201520/mp-usedVehicles#13]
Revisar el unicode para que en las páginas se desplieguen bien las tíldes y las ñs

**Comment by carmudgeon** [comment]
![captura1](https://cloud.githubusercontent.com/assets/2287052/10115348/92a857ea-63c9-11e5-99bc-789b257322e1.PNG)

**Comment by carmudgeon** [comment]
Se corrigen los formatos de las páginas
