### ISSUE TITLE
Claridad ante requerimiento 8

### ISSUE THREAD

**Issue by djimenez13** [MISO4203-201520/mp-usedVehicles#15]
Inquietud para que la aclare el cliente (profesora y/o monitor).

Respecto al req-08 de busqueda ofertas, quisiera que me definieran el alcance de ese requerimiento, es decir, ¿la idea es colocar una input text donde se coloque un nombre de un producto y se muestre si ese producto buscado tiene ofertas? ¿O si se muestra en una pantalla las ofertas que se encuentran activas al día de hoy? ¿O si se coloca un distintivo (imagen o algo) en los productos que tienen oferta dentro del catálogo que se muestra con todos los productos?

**Comment by rcasalla** [comment]
Oferta no se refiere a lo que está en "ganga" sino a lo que se está ofreciendo

**Comment by djimenez13** [comment]
Que pena profesora. Sigo sin entender. Si es lo que se está ofreciendo, ¿vendría siendo el catalogo de productos que se le muestra al cliente?
Personalmente, había comenzado a construir la funcionalidad donde se puede visualizar los productos del catálogo que tienen una oferta vigente, por ejemplo, un carro "Toyota land Cruiser" tiene una oferta que por la compra de éste, se le "obsequia al cliente un kit de carretera y un bono de mantenimiento por 6 meses".
Adicionalmente, podría buscar a través de una palabra clave (keyword) los productos que se encuentren con ofertas vigentes, por ejemplo, si busco a través del keyword "Chevrolet", el sistema busca todos los productos que tengan la palabra "Chevrolet" y que se encuentren con ofertas vigentes.

Si no es así, por favor ilustrarnos que funcionalidad esperaría el cliente respecto al req-08 para comenzar a construirla desde ya.

**Comment by djimenez13** [comment]
Luego de consultar con el monitor de la clase (Jhonatan), aclara que lo que necesita como cliente es que se construya una búsqueda avanzada a través de la cual se puedan ubicar los productos con base en varios criterios de búsqueda.
